; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = home

[env]
platform = espressif32 @ 6.10.0
board = esp32-c3-devkitc-02
framework = arduino

board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv
upload_speed = 921600
monitor_speed = 115200
; change microcontroller
board_build.mcu = esp32c3
; change MCU frequency
board_build.f_cpu = 160000000L

[env:home]
upload_port = COM10
lib_deps = gyverlibs/mString@^1.7.3

[env:work]
upload_port = COM9
lib_deps = gyverlibs/mString@^1.7.3


[env:laptop]
upload_port = COM3
lib_deps = gyverlibs/mString@^1.7.3
